### ISSUE TITLE
Patching setup.py not required

### ISSUE THREAD

**Issue by carterbox** [conda-forge/spikingjelly-feedstock#1]
Hi @Tobias-Fischer,

I noticed that you are patching this package to prevent pip from installing dependencies. This patch is not required. Just add the `--no-deps` option to `pip install`. Consider removing this patch during the next rebuild.

https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-deps

Cheers!

**Comment by Tobias-Fischer** [comment]
Hiya, thanks for this! Are you happy to open a pull request?

**Comment by Tobias-Fischer** [comment]
I think the issue is that the requirements.txt does not exist in the package, and that it'll still try to read it in the setup.py even with no-deps

**Comment by carterbox** [comment]
> I think the issue is that the requirements.txt does not exist in the package, and that it'll still try to read it in the setup.py even with no-deps

Oh! You're right. I didn't realize that the pypi source distribution was incomplete. I was looking at the source directly on GitHub.
